//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class ExpenseCategory
    {
        [Required]
        [Remote("CheckExpenseCategoryExist", "Stock", ErrorMessage = "Category Already Exist")]
        public string Category { get; set; }
        [Required]
        public string Description { get; set; }
    }
}
